name: CI/CD

on:
#   pull_request:
#     branches:
#       - master # CI (pr validation)
#     paths:
#       - "src/**"  
  push:
    branches:
      - master # CI (ci package)
    paths:
      - "src/**"        
    tags:
      - v\\d+\\.\\d+     # CD (release package)

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100-rc.1'
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}
    - run: dotnet build src/AspNetCore.ApiVersioning -c Release
    # - run: dotnet test test/AspNetCore.ApiVersioning.Tests -c Release
    - run: dotnet pack src/AspNetCore.ApiVersioning -c Release
    - run: dotnet nuget push src/AspNetCore.ApiVersioning/bin/Release/*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
      if: github.event_name == 'push' && startswith(github.ref, 'refs/heads')
    - run: dotnet nuget push src/AspNetCore.ApiVersioning/bin/Release/*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
      if: github.event_name == 'push' && startswith(github.ref, 'refs/tags')
    - run: dotnet nuget push src/AspNetCore.ApiVersioning/bin/Release/*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
      if: github.event_name == 'pull_request' && startswith(github.ref, 'refs/tags')
